### ISSUE TITLE
logs must be in english

### ISSUE THREAD

**Issue by ravellom** [yjx0003/UBUMonitor#123]
Facilidades por tan completa y profesional herramienta.
Algunas veces cuando trato de conectarme a algún curso dentro de un servidor me dice que los logs deben estar en inglés “logs must be in english” y no carga el curso.
Me gustaría colaborar con el proyecto. Es posible?
Mis datos: 
Dr. Raidell Avello Martínez
Profesor Titular, Departamento de Informática.
Grupo de Investigación sobre Tecnologías EMergentes para el Aprendizaje (GITEM@)
Universidad de Cienfuegos, Cuba.
Editor adjunto de RED. Revista de Educación a Distancia
ORCID: http://orcid.org/0000-0001-7200-632X
Saludos

**Comment by yjx0003** [comment]
Por lo que veo ese error se lanza cuando al descargar el CSV en ingles de los registros del curso no encuentra ninguna de las columnas: Time, User full name, Affected user, Event context, Component, Event name, Description, Origin, IP address. 

Si solo ocurre en cursos en concreto, puede ser debido a que el CSV de ese curso en concreto esté corrupto.

**Comment by ravellom** [comment]
Estoy de acuerdo, lo raro es que en un propio servidor solo ocurra con algunos cursos, se supone que los datos almacenados estén todos iguales. 
Pero yo me he enfrentado a problemas con los logs en csv, que el campo Hora por ejemplo, lo carga como “ï..Hora” con algunas funciones de R y Python, quizás en la carga de los logs se podía especificar algún parámetro para esto.
Saludos

**Comment by yjx0003** [comment]
Los caracteres iniciales extraños al principio de Hola es porque el CSV tiene el caracter BOM. Al parsear con las funcioens de CSV se le debe indicar que existe ese caracter para ignorarlo. En UBUMonitor ese problema no debería existir porque el error es que no detecta NINGUNO de los nombres de las columnas que he indicado.

Tendría que ver los CSV con los cursos que tienes problemas y quizás se añada en un futuro que ignore los registros si no se ha podido parsear ni trabajar con ellos.

**Comment by ravellom** [comment]
Disculpe el planteamiento erróneo de este issue, es que probé varios servidores y pensé que en el mismo había un curso que se cargó, pero no es correcto, o sea, en el servidor de postgrado ningún curso se carga, todos retornan este error. 
Por lo tanto, la solución está en configurar el server para que los registros estén en inglés, no?
De todas formas, le adjunto la imagen para que tenga la evidencia.
Sería bueno poder parsear los logs y si están en español cargarlos también, es solo una sugerencia, pues en Latinoamérica se puede encontrar este problema y sería un sesgo no poder usar tan útil aplicación por esta causa.
Gracias de antemano por su atención.
<img width="654" alt="ubumonitor_error3" src="https://user-images.githubusercontent.com/65437692/123821572-849f7180-d8c9-11eb-95b5-2f771b67ddb4.png">

**Comment by yjx0003** [comment]
¿No está el inglés como opción de idioma en el desplegable del servidor de Moodle?
![imagen](https://user-images.githubusercontent.com/33248320/123854319-d9210c00-d91e-11eb-900c-c5a14cc826d2.png)

Porque cuando hice pruebas en un servidor de Moodle local, el inglés no me dejaba eliminarlo de las opciones en la configuración del servidor. Por eso deducí que lo más sencillo era parsear los registros en inglés para todos los Moodles del mundo.

**Comment by ravellom** [comment]
Solucionado
Tiene toda la razón:
Hay que entrar a “Editar ajustes” del curso en cuestión (donde tiene acceso el profesor, o sea no hay problema con permisos de administración), luego en Apariencia/Forzar idioma y asignar English. Luego ya UBUMonitor puede extraer los logs sin problema y el profesor puede regresar la configuración del curso a español nuevamente.
Lo expliqué con detalles para si es alguna duda de otro profesor (no es para el desarrollador).
Gracias por su atención.

**Comment by yjx0003** [comment]
También con la opción de "No forzar" es suficiente para que funcione y no cambiar cada vez las opciones de apariencia del curso cada vez que uses la aplicación. Además el usuario puede elegir qué idioma usar dentro del curso.
