### ISSUE TITLE
bug:error de carga de registros

### ISSUE THREAD

**Issue by clopezno** [yjx0003/UBUMonitor#125]
En dos cursos de una instancia de Moodle Cloud  https://freva21.moodlecloud.com/ se estan produciendo problemas de carga de los registros de log.

Adjunto excepciones de los cursos.
Título del curso Acercamiento al mundo vegetariano para estudiantes

![ErrorUBUMonitoralcargar registros](https://user-images.githubusercontent.com/1453744/143613320-4deabda0-bffc-4b4f-9fdb-dbd22793c012.png)

Título del curso Dieta Gluten free

![ubumonitorDescargadatos](https://user-images.githubusercontent.com/1453744/143613398-87654ece-9325-47ed-bdee-acfd654404fb.png)

**Comment by clopezno** [comment]
Por si hay que replicar los errores informo que los cursos están en la una instancia temporal de moodle cloud que estará disponible hasta el 10 de diciembre.

**Comment by yjx0003** [comment]
Es un problema al parsear ese numero a integer. Puedes descargarte el CSV de los registros y comprobar donde aparece ese número en la columna Descripción.

De todos modos cambiare en caso de que falle a parsear alguna línea del CSV lo ignore y siga adelanta.

**Comment by clopezno** [comment]
He creado un usuario @yjx0003  en https://freva21.moodlecloud.com/ y te he matriculado en los dos cursos como profesor por si quieres probarlo.
Respecto al otro error  _Logs must be in english_ ¿sabes identificarlo?

**Comment by yjx0003** [comment]
Perdón, había entendido que eran dos errores en cascada. 
En cuanto al error de Logs must be in english es porque en el curso está forzado el idioma al español. El curso deberia estar con la opción de No forzar o en inglés para los registros.
![imagen](https://user-images.githubusercontent.com/33248320/143836916-31aa366d-56c4-4d70-bb61-8948a635ae3e.png)
Cambiaré ese mensaje de error por otro más específico mencionando esto.

Sobre el error del otro curso es por el componente BigBlueButton que los identificadores alfanúmericos, tendre que echar un vistazo en la expresión regular. 

> The user with id '22' has viewed a recording with id '721eb77dd5773f6c041800a477249deeb6850be7-1637182515208' from the course id '6'.

Gracias por el aviso.

**Comment by clopezno** [comment]
Yi, gracias a tí  por tu buena explicación del error y tu rápida respuesta.
