### ISSUE TITLE
Bug exportación datos de un evento a csv

### ISSUE THREAD

**Issue by clopezno** [yjx0003/UBUMonitor#63]
Adjunto captura de pantalla con la descripción del error
![imagen](https://user-images.githubusercontent.com/1453744/72063903-05843b00-32db-11ea-855c-38c3b45119af.png)

**Comment by rmartico** [comment]
Hola Carlos,

En el directorio /log tendrás un fichero UBUMonitor v2.5.0-stable.log (o similar con extensión .log).

Si puedes mandármelo en un .zip (o bien lo quieres cortar antes de enviar para no violar mucho la LOPD y limitar solo a la traza particular del error), nos dará más pistas de qué esta pasando.

En principio la exportación CSV guarda todos los datos ya cargados en memoria y salvo problemas disco/permisos no debería generar errores porque no hacemos nada muy raro. Pero seguro que algo se nos ha pasado…

Saludos,
Raúl

De: Carlos López [mailto:notifications@github.com]
Enviado el: jueves, 09 de enero de 2020 12:30
Para: yjx0003/UBUMonitor
CC: Subscribed
Asunto: [yjx0003/UBUMonitor] Bug exportación datos de un evento a csv (#63)


Adjunto captura de pantalla con la descripción del error
[Imagen quitada por el remitente. imagen]<https://user-images.githubusercontent.com/1453744/72063903-05843b00-32db-11ea-855c-38c3b45119af.png>

**Comment by clopezno** [comment]
Adjunto el fichero de log después de volver a reproducir el error
[UBUMonitor v2.5.0-stable.log](https://github.com/yjx0003/UBUMonitor/files/4107674/UBUMonitor.v2.5.0-stable.log)

**Comment by yjx0003** [comment]
> 
> 
> Adjunto el fichero de log después de volver a reproducir el error
> [UBUMonitor v2.5.0-stable.log](https://github.com/yjx0003/UBUMonitor/files/4107674/UBUMonitor.v2.5.0-stable.log)

El error del CSV ya está arreglado para la próxima versión. También estoy viendo que hay logs que no están contabilizados, también se añadirá para la proxima versión.
