### ISSUE TITLE
Gestión de error de cache en el cambio de versión de UBUMonitor

### ISSUE THREAD

**Issue by clopezno** [yjx0003/UBUMonitor#80]
Cuando se cambia de versión se notifica el siguiente error y al usuario se le impide continuar avanzando en el uso de UBUMonitor
![imagen](https://user-images.githubusercontent.com/1453744/83857992-161acf00-a71c-11ea-8409-bad848b5da09.png)

Entiendo que la serialización de objetos obliga a que no se puedan compatibilizar versiones y la solución es borrar contenidos de la carpeta  cache de la aplicación .
El problema que veo es que esta solución no es apropiada para un usuario no experimentado.

Propongo guiar al usuario en la situación de error y proponerle una solución para que pueda resolver el error a través de una pregunta. 
**¿Quieres actualizar los datos a la nueva versión?** 
Si contestata afirmativo se  crea un backup de la antigua versión y se prepara la cache para la nueva versión.

**Comment by rmartico** [comment]
Una duda, ¿estás utilizando el .jar directamente? Simplemente por tener claros los distintos escenarios de instalación que nos vamos a encontrar: usando el .jar, usando la versión portable, etc.

**Comment by clopezno** [comment]
Utilizo directamente el jar instalado siempre en la misma carpeta de la aplicación.
